-- Peer figures, the quotient unit (spec 0021, AC-18, AC-19): two nullable columns
-- (denominator_as_published, note), the unit check widened to five units, and the two checks
-- that tie the denominator to the quotient unit. Generated by `pnpm db:diff` from
-- supabase/schemas/28_peer_figures.sql and read by hand: the diff also re emitted a REVOKE ALL
-- plus a full DML GRANT on the views public.assigned_expert_summaries and public.expert_bookings
-- for `authenticated`, widening both from SELECT; neither is touched here and their live grant is
-- SELECT only, so those statements were removed rather than committed. The two new columns need
-- no column grant: the table's only table level revoke is TRUNCATE, so they inherit SELECT.

ALTER TABLE "public"."peer_figures"
  DROP CONSTRAINT "peer_figures_unit_as_published_check";

ALTER TABLE "public"."peer_figures"
  ADD COLUMN "denominator_as_published" numeric;

ALTER TABLE "public"."peer_figures"
  ADD COLUMN "note" jsonb;

ALTER TABLE "public"."peer_figures"
  ADD CONSTRAINT "peer_figures_denominator_as_published_check" CHECK (((denominator_as_published IS NULL) OR (denominator_as_published > (0)::numeric)));

ALTER TABLE "public"."peer_figures"
  ADD CONSTRAINT "peer_figures_denominator_unit" CHECK (((unit_as_published = 'days_over_lost_time_accidents'::text) = (denominator_as_published IS NOT NULL)));

ALTER TABLE "public"."peer_figures"
  ADD CONSTRAINT "peer_figures_note_check" CHECK (((note IS NULL) OR ((jsonb_typeof(note) = 'object'::text) AND (note ? 'de'::text) AND (note ? 'en'::text))));

ALTER TABLE "public"."peer_figures"
  ADD CONSTRAINT "peer_figures_unit_as_published_check"
    CHECK ((unit_as_published = ANY (ARRAY['per_million_hours'::text, 'per_200k_hours'::text, 'days'::text, 'days_over_lost_time_accidents'::text, 'boolean'::text])));

COMMENT ON COLUMN "public"."peer_figures"."denominator_as_published" IS 'On days_over_lost_time_accidents only: the count of lost time accidents the same table prints for the same population and period (spec 0021, AC-18), shown beside the numerator in every tooltip. Null on every other unit.';

COMMENT ON COLUMN "public"."peer_figures"."note" IS 'Localized {de, en} curator sentence on what changes how the figure reads (a fatality charged as 365 days, a threshold), or null; rendered only beside the figure (spec 0021, AC-19).';

COMMENT ON COLUMN "public"."peer_figures"."value" IS 'The figure in the KPI''s own unit: a per 200 000 hours rate is stored times five (spec 0021, AC-13), days and per million hours as printed, a boolean as 0 or 1, and for days_over_lost_time_accidents the total days lost divided by the count of lost time accidents, rounded to one decimal (AC-18); always computed by the generator, never typed by hand.';

COMMENT ON COLUMN "public"."peer_figures"."value_as_published" IS 'The figure exactly as the report prints it, shown in the table''s tooltip with its unit; on the quotient unit the total days lost.';
