/**
 * Country codes for the contact directory (spec 0018, AC-2, Value sourcing). `COUNTRY_CODES` is
 * the ISO 3166 alpha 2 list; `COUNTRY_NAMES` maps the spellings the purchased list uses to a
 * code and grows from the unmapped names a dry run reports. A row whose spelling is not here is
 * skipped and counted, never guessed: the lawyer clears countries by code, so a wrong map would
 * load a row into a jurisdiction nobody cleared. Alias free, Node only (the import script runs
 * it under type stripping).
 */

export const COUNTRY_CODES = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BV",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HM",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TF",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "UM",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
] as const;

export type CountryCode = (typeof COUNTRY_CODES)[number];

const CODE_SET: ReadonlySet<string> = new Set(COUNTRY_CODES);

/** True for a valid ISO 3166 alpha 2 code, upper case. Any context. */
export function isCountryCode(value: string): value is CountryCode {
  return CODE_SET.has(value);
}

/**
 * The spellings the list uses, lower cased with trailing punctuation removed (see
 * `countryLookupKey`), mapped to a code. A two letter value that is itself a valid code needs no
 * entry. Ambiguous spellings ("Virgin Islands", "Republic Of China", "Santiago", "West Indies")
 * are deliberately absent: they stay unmapped and reported rather than guessed.
 */
export const COUNTRY_NAMES: Readonly<Record<string, CountryCode>> = {
  // The bulk of the list.
  "united states": "US",
  "united states of america": "US",
  "united states of": "US",
  "united states of am": "US",
  "united states of ame": "US",
  "united states od america": "US",
  "united states (us)": "US",
  "united state": "US",
  "united stated": "US",
  "united staes": "US",
  "united statesu": "US",
  "unitd states": "US",
  "unitted states": "US",
  "unite states": "US",
  "untied states": "US",
  "uuited stgates": "US",
  unitedstates: "US",
  unitedstatesofamerica: "US",
  "united unitedstatesstates": "US",
  "u.s.a": "US",
  "u s": "US",
  u: "US",
  usa: "US",
  usaa: "US",
  ohio: "US",
  mexico: "MX",
  mexikco: "MX",
  mexco: "MX",
  puebla: "MX",
  queretaro: "MX",
  sinaloa: "MX",
  brazil: "BR",
  brazsl: "BR",
  canada: "CA",
  "canada (ca)": "CA",
  cananda: "CA",
  canda: "CA",
  canadda: "CA",
  australia: "AU",
  austalia: "AU",
  austraila: "AU",
  austrailia: "AU",
  malaysia: "MY",
  indonesia: "ID",
  indoneisa: "ID",
  jakarta: "ID",
  singapore: "SG",
  sngapore: "SG",
  "singapore 119958": "SG",
  spain: "ES",
  madrid: "ES",
  france: "FR",
  francia: "FR",
  germany: "DE",
  ger: "DE",
  obernburg: "DE",
  india: "IN",
  incia: "IN",
  "new delhi": "IN",
  gujrat: "IN",
  netherlands: "NL",
  netherland: "NL",
  nederland: "NL",
  nederlands: "NL",
  thailand: "TH",
  bangkok: "TH",
  rayong: "TH",
  "united kingdom": "GB",
  "united kingdon": "GB",
  "united kngdom": "GB",
  "united kingdown": "GB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  "northern ireland": "GB",
  argentina: "AR",
  aregentina: "AR",
  colombia: "CO",
  olombia: "CO",
  "saudi arabia": "SA",
  "kingdom of saudi arabia": "SA",
  saudi: "SA",
  ksa: "SA",
  peru: "PE",
  perú: "PE",
  lima: "PE",
  chile: "CL",
  philippines: "PH",
  philippine: "PH",
  phillippines: "PH",
  phils: "PH",
  belgium: "BE",
  belgique: "BE",
  begium: "BE",
  jumet: "BE",
  "new zealand": "NZ",
  italy: "IT",
  italie: "IT",
  portugal: "PT",
  switzerland: "CH",
  schweiz: "CH",
  suisse: "CH",
  "costa rica": "CR",
  "south korea": "KR",
  "korea, republic of": "KR",
  "korea, rebublic of": "KR",
  "republic of korea": "KR",
  "rep. of korea": "KR",
  korera: "KR",
  "puerto rico": "PR",
  "usa puerto rico": "PR",
  "usa puero rico": "PR",
  "puerto rico usa": "PR",
  "dorado, puerto rico": "PR",
  "dominican republic": "DO",
  "dominicanb republic": "DO",
  "republica dominicana": "DO",
  "santo domingo": "DO",
  panama: "PA",
  poland: "PL",
  bolivia: "BO",
  boliva: "BO",
  guatemala: "GT",
  "viet nam": "VN",
  vietnam: "VN",
  "united arab emirates": "AE",
  "united arabic emirates": "AE",
  "abu dhabi": "AE",
  turkey: "TR",
  türkiye: "TR",
  venezuela: "VE",
  ecuador: "EC",
  ukraine: "UA",
  austria: "AT",
  österreich: "AT",
  oostenrijk: "AT",
  "south africa": "ZA",
  "trinidad and tobago": "TT",
  "trinidad and tovago": "TT",
  "trinidad & tobago": "TT",
  "idad & tobago, west indies": "TT",
  trinidad: "TT",
  trinidda: "TT",
  "trinidad, wi": "TT",
  "trinidad w.i": "TT",
  ireland: "IE",
  "southern ireland": "IE",
  honduras: "HN",
  greece: "GR",
  grece: "GR",
  norway: "NO",
  finland: "FI",
  egypt: "EG",
  nicaragua: "NI",
  uruguay: "UY",
  luxembourg: "LU",
  qatar: "QA",
  denmark: "DK",
  sweden: "SE",
  "czech republic": "CZ",
  china: "CN",
  "p.r. china": "CN",
  prc: "CN",
  pakistan: "PK",
  paraguay: "PY",
  israel: "IL",
  isarel: "IL",
  kuwait: "KW",
  taiwan: "TW",
  "el salvador": "SV",
  bulgaria: "BG",
  hungary: "HU",
  "papua new guinea": "PG",
  png: "PG",
  japan: "JP",
  cambodia: "KH",
  "kingdom of cambodia": "KH",
  jamaica: "JM",
  oman: "OM",
  "sultanate of oman": "OM",
  romania: "RO",
  roemenie: "RO",
  kazakhstan: "KZ",
  bahrain: "BH",
  "kingdom of bahrain": "BH",
  nigeria: "NG",
  ghana: "GH",
  angola: "AO",
  "russian federation": "RU",
  russia: "RU",
  gabon: "GA",
  slovakia: "SK",
  "new caledonia": "NC",
  algeria: "DZ",
  algerie: "DZ",
  algérie: "DZ",
  morocco: "MA",
  mozambique: "MZ",
  serbia: "RS",
  libya: "LY",
  lybia: "LY",
  bahamas: "BS",
  cyprus: "CY",
  kenya: "KE",
  slovenia: "SI",
  "hong kong": "HK",
  hongkong: "HK",
  estonia: "EE",
  "ivory coast": "CI",
  suriname: "SR",
  lebanon: "LB",
  libanon: "LB",
  tanzania: "TZ",
  lichtenstein: "LI",
  liechtenstein: "LI",
  croatia: "HR",
  curazao: "CW",
  "democratic republic of congo": "CD",
  congo: "CG",
  "sao tome e principe": "ST",
  tunisia: "TN",
  "equatorial guinea": "GQ",
  namibia: "NA",
  cuba: "CU",
  albania: "AL",
  samoa: "WS",
  "saint lucia": "LC",
  "gu 96932": "GU",
};

/**
 * The lookup key of a raw country cell: lower case, trimmed, inner whitespace collapsed, trailing
 * dots and commas dropped, so "Malaysia." and "Nicaragua," match their clean spellings. Any
 * context.
 */
export function countryLookupKey(raw: string): string {
  return raw
    .replace(/\s+/g, " ")
    .trim()
    .replace(/[.,]+$/, "")
    .trim()
    .toLowerCase();
}

/**
 * The alpha 2 code for a raw country cell, or null when the spelling is unmapped: a mapped
 * spelling, else a two letter value that is itself a valid code ("Es", "Gb"). Never a guess.
 * Any context.
 */
export function countryCode(raw: string): CountryCode | null {
  const key = countryLookupKey(raw);
  if (key.length === 0) return null;
  const mapped = COUNTRY_NAMES[key];
  if (mapped !== undefined) return mapped;
  const upper = key.toUpperCase();
  return key.length === 2 && isCountryCode(upper) ? upper : null;
}
