import type { ContentFile, ContentItem, LocalizedText } from "./content-schema.ts";
import { itemIdOf, versionKeyOf } from "./content-schema.ts";

/**
 * Renders the questionnaire seed migration (spec 0019, AC-2): one upsert per version and per
 * item, never a delete, so a rerun changes no row count and a text correction within a version
 * is a new generated migration. Items are emitted in position order, so every parent (a smaller
 * position) is inserted before its children and the self reference resolves. Pure; the
 * `questionnaires-migration` script writes the result to supabase/migrations/.
 */

/** A SQL string literal with single quotes doubled. Pure. */
function literal(value: string | null): string {
  return value === null ? "null" : `'${value.replaceAll("'", "''")}'`;
}

/** A jsonb literal of any JSON value. Pure. */
function jsonb(value: unknown): string {
  return `${literal(JSON.stringify(value))}::jsonb`;
}

/** A jsonb literal of a `{de, en}` pair, or `null`. Pure. */
function localized(text: LocalizedText | null): string {
  return text === null ? "null" : jsonb({ de: text.de, en: text.en });
}

const VERSION_COLUMNS = [
  "key",
  "questionnaire_key",
  "version",
  "title",
  "sections",
  "item_count",
  "source_note",
] as const;

const ITEM_COLUMNS = [
  "id",
  "version_key",
  "position",
  "parent_id",
  "section_key",
  "group_key",
  "label",
  "rateable",
  "title",
  "requirement",
  "question",
  "de_reviewed",
] as const;

function updateSet(columns: readonly string[], conflictKey: string): string {
  return columns
    .filter((column) => column !== conflictKey)
    .map((column) => `${column} = excluded.${column}`)
    .join(", ");
}

/** The upsert of the version row of a content file. Pure. */
export function renderVersionUpsert(file: ContentFile): string {
  const values = [
    literal(versionKeyOf(file)),
    literal(file.key),
    String(file.version),
    localized(file.title),
    jsonb(
      file.sections.map((section) => ({
        key: section.key,
        label: section.label,
        title: section.title,
        groups: section.groups.map((group) => ({
          key: group.key,
          label: group.label,
          title: group.title,
        })),
      })),
    ),
    String(file.items.length),
    literal(file.sourceNote),
  ];
  return [
    `insert into public.questionnaire_versions (${VERSION_COLUMNS.join(", ")})`,
    `values (${values.join(", ")})`,
    `on conflict (key) do update set ${updateSet(VERSION_COLUMNS, "key")};`,
  ].join("\n");
}

/** The upsert of one item. Pure. */
export function renderItemUpsert(versionKey: string, item: ContentItem): string {
  const values = [
    literal(itemIdOf(versionKey, item.position)),
    literal(versionKey),
    String(item.position),
    item.parentPosition === null ? "null" : literal(itemIdOf(versionKey, item.parentPosition)),
    literal(item.sectionKey),
    literal(item.groupKey),
    literal(item.label),
    item.rateable ? "true" : "false",
    localized(item.title),
    localized(item.requirement),
    localized(item.question),
    item.deReviewed ? "true" : "false",
  ];
  return [
    `insert into public.questionnaire_items (${ITEM_COLUMNS.join(", ")})`,
    `values (${values.join(", ")})`,
    `on conflict (id) do update set ${updateSet(ITEM_COLUMNS, "id")};`,
  ].join("\n");
}

/** The whole migration file over every content file, in the order given. Pure. */
export function renderQuestionnaireMigration(
  files: readonly ContentFile[],
  generatedAt: Date,
): string {
  const header = [
    "-- Questionnaire seed (spec 0019, AC-2), generated by `pnpm questionnaires:migration` on",
    `-- ${generatedAt.toISOString()} from src/features/assessments/content/*.json.`,
    "-- Do not edit by hand: change the content file (or rerun `pnpm questionnaires:build`) and",
    "-- generate again. Every statement is an upsert keyed on the version key or the item id, so a",
    "-- rerun changes no row count; nothing is ever deleted, because an assessment pinned to a",
    "-- version keeps reading its items for life.",
    "",
  ];
  const blocks = files.flatMap((file) => {
    const versionKey = versionKeyOf(file);
    const items = [...file.items].sort((a, b) => a.position - b.position);
    return [
      `-- ${versionKey}: ${file.sections.length} sections, ${items.length} items`,
      renderVersionUpsert(file),
      ...items.map((item) => renderItemUpsert(versionKey, item)),
      "",
    ];
  });
  return [...header, ...blocks].join("\n");
}
